include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 140

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - lib/l10n/app_localizations*.dart

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
