import 'package:flutter/widgets.dart';
import 'package:lottie/lottie.dart';

import '../motion/motion.dart';

/// Every Lottie the app ships, generated by tool/lottie/build_lottie.py.
abstract final class BobaLotties {
  static const splashLogo = 'splash_logo';
  static const loadingPearls = 'loading_pearls';
  static const successCheck = 'success_check';
  static const confetti = 'confetti';
  static const emptyCup = 'empty_cup';
  static const stamp = 'stamp';
  static const statusReceived = 'status_received';
  static const statusBrewing = 'status_brewing';
  static const statusReady = 'status_ready';
  static const statusDone = 'status_done';
  static const onboardBuild = 'onboard_build';
  static const onboardOrder = 'onboard_order';
  static const onboardStamps = 'onboard_stamps';

  static const all = [
    splashLogo, loadingPearls, successCheck, confetti, emptyCup, stamp, //
    statusReceived, statusBrewing, statusReady, statusDone, //
    onboardBuild, onboardOrder, onboardStamps,
  ];

  static String asset(String name) => 'assets/lottie/$name.json';
}

/// A Lottie from assets/lottie that respects reduced motion: it then shows a
/// single still frame ([stillProgress]) instead of playing.
class BobaLottie extends StatelessWidget {
  const BobaLottie(
    this.name, {
    super.key,
    this.size,
    this.width,
    this.height,
    this.repeat = true,
    this.stillProgress = 1,
    this.controller,
    this.onLoaded,
    this.fit = BoxFit.contain,
  });

  final String name;
  final double? size;
  final double? width;
  final double? height;
  final bool repeat;
  final BoxFit fit;

  /// Frame to show when motion is reduced. One-shot animations end on their
  /// final pose, so 1 is the right default.
  final double stillProgress;
  final Animation<double>? controller;
  final void Function(LottieComposition composition)? onLoaded;

  @override
  Widget build(BuildContext context) {
    final reduced = context.reduceMotion;
    final w = width ?? size;
    final h = height ?? size;
    return ExcludeSemantics(
      child: Lottie.asset(
        BobaLotties.asset(name),
        width: w,
        height: h,
        fit: fit,
        repeat: repeat,
        controller: reduced ? AlwaysStoppedAnimation(stillProgress) : controller,
        animate: reduced ? false : null,
        frameRate: FrameRate.max,
        onLoaded: onLoaded,
        errorBuilder: (context, error, stackTrace) => SizedBox(width: w, height: h),
      ),
    );
  }
}
